/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=PagesEnv pages-configuration.d.ts` (hash: 9b5dc86858098a87d8245bb3ec637965)
interface __BaseEnv_PagesEnv {
	CHECKIN_API: Fetcher /* swing-checkin-sync */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_PagesEnv {}
}
interface PagesEnv extends __BaseEnv_PagesEnv {}
