/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 0c7021c25cc13f3e6ea92c4d9a86cdb9)
interface __BaseEnv_Env {
	MEMBER_CACHE: KVNamespace;
	EVENTS_DB: D1Database;
	MEMBER_SEARCH_RATE_LIMITER: RateLimit;
	RSVP_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NOTION_MEMBERS_DATA_SOURCE_ID: "6963065b-1352-4663-bf1a-fb3ed656e018";
	NOTION_EVENTS_DATA_SOURCE_ID: "687e0df9-8bc6-4383-99b0-9a7ffcbaf5a5";
	NOTION_REQUESTS_PER_SECOND: "3";
	GOOGLE_SPREADSHEET_ID: "1LolWpgKRUjYE45S3UrxWLPqtek0FfEmlcbKNr4Mm2AQ";
	GOOGLE_SHEET_NAME: "Check-ins";
	TIME_ZONE: "America/New_York";
	ACCESS_TEAM_DOMAIN: "swing-syndicate-cornell.cloudflareaccess.com";
	ACCESS_AUD: "edff3a8c97b455c985deb5d34b4cfd6f81fc603b92aa4c3f0fe694434f556229";
	CLOUDFLARE_ACCOUNT_ID: "826a8805e6c445803da24e740d6912e3";
	REDIRECT_HOSTNAME: "swingsyndicate.club";
	REDIRECT_LIST_ID: "1d0b827660564acc937c13b954fc263e";
	NOTION_TOKEN: string;
	GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
	GOOGLE_PRIVATE_KEY: string;
	GOOGLE_PLACES_API_KEY: string;
	REDIRECT_API_TOKEN: string;
	CHECKIN_GUARD: DurableObjectNamespace<import("./src/worker").CheckinGuard>;
	ATTENDANCE_SYNC: DurableObjectNamespace<import("./src/worker").AttendanceSync>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "CheckinGuard" | "AttendanceSync";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOTION_MEMBERS_DATA_SOURCE_ID" | "NOTION_EVENTS_DATA_SOURCE_ID" | "NOTION_REQUESTS_PER_SECOND" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_NAME" | "TIME_ZONE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CLOUDFLARE_ACCOUNT_ID" | "REDIRECT_HOSTNAME" | "REDIRECT_LIST_ID" | "NOTION_TOKEN" | "GOOGLE_SERVICE_ACCOUNT_EMAIL" | "GOOGLE_PRIVATE_KEY" | "GOOGLE_PLACES_API_KEY" | "REDIRECT_API_TOKEN">> {}
}
