/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: a2a02a92d3d71dc9fc57d974913ba5a9)
interface __BaseEnv_Env {
	MEMBER_CACHE: KVNamespace;
	MEMBER_SEARCH_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	NOTION_MEMBERS_DATA_SOURCE_ID: "6963065b-1352-4663-bf1a-fb3ed656e018";
	NOTION_EVENTS_DATA_SOURCE_ID: "687e0df9-8bc6-4383-99b0-9a7ffcbaf5a5";
	GOOGLE_SPREADSHEET_ID: "1LolWpgKRUjYE45S3UrxWLPqtek0FfEmlcbKNr4Mm2AQ";
	GOOGLE_SHEET_NAME: "Check-ins";
	TIME_ZONE: "America/New_York";
	NOTION_TOKEN: string;
	GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
	GOOGLE_PRIVATE_KEY: string;
	CHECKIN_GUARD: DurableObjectNamespace<import("./check-in/worker/index").CheckinGuard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./check-in/worker/index");
		durableNamespaces: "CheckinGuard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOTION_MEMBERS_DATA_SOURCE_ID" | "NOTION_EVENTS_DATA_SOURCE_ID" | "GOOGLE_SPREADSHEET_ID" | "GOOGLE_SHEET_NAME" | "TIME_ZONE" | "NOTION_TOKEN" | "GOOGLE_SERVICE_ACCOUNT_EMAIL" | "GOOGLE_PRIVATE_KEY">> {}
}
